version: '3.7'

services:
  web:
    image: snaket2628/website
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - "80:80"
