version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: /root/Docker-Swarm-Web-Application-Deployment/Dockerfile
    image: website:v1
    restart: unless-stopped
    
    ports:
      - "80:80"
    deploy:
      replicas: 3
