version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: snaket2628/website
    restart: unless-stopped

    ports:
      - "80:80"
    deploy:
      replicas: 3
